name: CI

on:
  pull_request:
    branches: 
      - main

jobs: 
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm run lint

      - name: Install Prettier globally 
        run: npm install -g prettier 

      - name: Formatter (Prettier)
        run: npm run prettier
      
      - name: Build
        run: npm run build
