name: Node.js CI

on:
  push:
    branches: [dev, stage, prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install
    
    - name: Lint with ESLint
      run: ng lint

    - name: Format with Prettier
      run: npm run prettier

    - name: Test with Jest
      env:
        CI: true
      run: npm run test

    - name: Build
      run: npm run build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET_DEV: ${{ secrets.AWS_S3_BUCKET_DEV }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
        SOURCE_DIR: 'dist'
        DEST_DIR: 'dev'
      if: github.ref == 'refs/heads/dev'

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET_STAGE: ${{ secrets.AWS_S3_BUCKET_STAGE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
        SOURCE_DIR: 'dist'
        DEST_DIR: 'stage'
      if: github.ref == 'refs/heads/stage'

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET_PROD: ${{ secrets.AWS_S3_BUCKET_PROD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
        SOURCE_DIR: 'dist'
        DEST_DIR: 'prod'
      if: github.ref == 'refs/heads/prod'
